project:
  type: website
  output-dir: docs

website:
  title: "Статьи"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bank
        href: https://www.asu.ru
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

